# Generated by Django 5.0.3 on 2024-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Título', models.CharField(max_length=100, verbose_name='Título')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('Descripción', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
